const form = document.querySelector('.formWithValidation')
const validateBtn = form.querySelector('.validateBtn')
const username = form.querySelector('.username')
const password = form.querySelector('.password')
const passwordConfirmation = form.querySelector('.passwordConfirmation')
const where = form.querySelector('.where')
const message = form.querySelector('.message')
const fields = form.querySelectorAll('.field')
